// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"enttest/ent/oauthuserinfo"
	"enttest/ent/predicate"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OAuthUserinfoQuery is the builder for querying OAuthUserinfo entities.
type OAuthUserinfoQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.OAuthUserinfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OAuthUserinfoQuery builder.
func (ouq *OAuthUserinfoQuery) Where(ps ...predicate.OAuthUserinfo) *OAuthUserinfoQuery {
	ouq.predicates = append(ouq.predicates, ps...)
	return ouq
}

// Limit adds a limit step to the query.
func (ouq *OAuthUserinfoQuery) Limit(limit int) *OAuthUserinfoQuery {
	ouq.limit = &limit
	return ouq
}

// Offset adds an offset step to the query.
func (ouq *OAuthUserinfoQuery) Offset(offset int) *OAuthUserinfoQuery {
	ouq.offset = &offset
	return ouq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ouq *OAuthUserinfoQuery) Unique(unique bool) *OAuthUserinfoQuery {
	ouq.unique = &unique
	return ouq
}

// Order adds an order step to the query.
func (ouq *OAuthUserinfoQuery) Order(o ...OrderFunc) *OAuthUserinfoQuery {
	ouq.order = append(ouq.order, o...)
	return ouq
}

// First returns the first OAuthUserinfo entity from the query.
// Returns a *NotFoundError when no OAuthUserinfo was found.
func (ouq *OAuthUserinfoQuery) First(ctx context.Context) (*OAuthUserinfo, error) {
	nodes, err := ouq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{oauthuserinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ouq *OAuthUserinfoQuery) FirstX(ctx context.Context) *OAuthUserinfo {
	node, err := ouq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OAuthUserinfo ID from the query.
// Returns a *NotFoundError when no OAuthUserinfo ID was found.
func (ouq *OAuthUserinfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ouq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{oauthuserinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ouq *OAuthUserinfoQuery) FirstIDX(ctx context.Context) int {
	id, err := ouq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OAuthUserinfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one OAuthUserinfo entity is not found.
// Returns a *NotFoundError when no OAuthUserinfo entities are found.
func (ouq *OAuthUserinfoQuery) Only(ctx context.Context) (*OAuthUserinfo, error) {
	nodes, err := ouq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{oauthuserinfo.Label}
	default:
		return nil, &NotSingularError{oauthuserinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ouq *OAuthUserinfoQuery) OnlyX(ctx context.Context) *OAuthUserinfo {
	node, err := ouq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OAuthUserinfo ID in the query.
// Returns a *NotSingularError when exactly one OAuthUserinfo ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ouq *OAuthUserinfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ouq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = &NotSingularError{oauthuserinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ouq *OAuthUserinfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := ouq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OAuthUserinfos.
func (ouq *OAuthUserinfoQuery) All(ctx context.Context) ([]*OAuthUserinfo, error) {
	if err := ouq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ouq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ouq *OAuthUserinfoQuery) AllX(ctx context.Context) []*OAuthUserinfo {
	nodes, err := ouq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OAuthUserinfo IDs.
func (ouq *OAuthUserinfoQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ouq.Select(oauthuserinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ouq *OAuthUserinfoQuery) IDsX(ctx context.Context) []int {
	ids, err := ouq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ouq *OAuthUserinfoQuery) Count(ctx context.Context) (int, error) {
	if err := ouq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ouq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ouq *OAuthUserinfoQuery) CountX(ctx context.Context) int {
	count, err := ouq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ouq *OAuthUserinfoQuery) Exist(ctx context.Context) (bool, error) {
	if err := ouq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ouq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ouq *OAuthUserinfoQuery) ExistX(ctx context.Context) bool {
	exist, err := ouq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OAuthUserinfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ouq *OAuthUserinfoQuery) Clone() *OAuthUserinfoQuery {
	if ouq == nil {
		return nil
	}
	return &OAuthUserinfoQuery{
		config:     ouq.config,
		limit:      ouq.limit,
		offset:     ouq.offset,
		order:      append([]OrderFunc{}, ouq.order...),
		predicates: append([]predicate.OAuthUserinfo{}, ouq.predicates...),
		// clone intermediate query.
		sql:  ouq.sql.Clone(),
		path: ouq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Account string `json:"account,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OAuthUserinfo.Query().
//		GroupBy(oauthuserinfo.FieldAccount).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ouq *OAuthUserinfoQuery) GroupBy(field string, fields ...string) *OAuthUserinfoGroupBy {
	group := &OAuthUserinfoGroupBy{config: ouq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ouq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ouq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Account string `json:"account,omitempty"`
//	}
//
//	client.OAuthUserinfo.Query().
//		Select(oauthuserinfo.FieldAccount).
//		Scan(ctx, &v)
//
func (ouq *OAuthUserinfoQuery) Select(fields ...string) *OAuthUserinfoSelect {
	ouq.fields = append(ouq.fields, fields...)
	return &OAuthUserinfoSelect{OAuthUserinfoQuery: ouq}
}

func (ouq *OAuthUserinfoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ouq.fields {
		if !oauthuserinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ouq.path != nil {
		prev, err := ouq.path(ctx)
		if err != nil {
			return err
		}
		ouq.sql = prev
	}
	return nil
}

func (ouq *OAuthUserinfoQuery) sqlAll(ctx context.Context) ([]*OAuthUserinfo, error) {
	var (
		nodes = []*OAuthUserinfo{}
		_spec = ouq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &OAuthUserinfo{config: ouq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ouq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ouq *OAuthUserinfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ouq.querySpec()
	return sqlgraph.CountNodes(ctx, ouq.driver, _spec)
}

func (ouq *OAuthUserinfoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ouq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ouq *OAuthUserinfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   oauthuserinfo.Table,
			Columns: oauthuserinfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauthuserinfo.FieldID,
			},
		},
		From:   ouq.sql,
		Unique: true,
	}
	if unique := ouq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ouq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthuserinfo.FieldID)
		for i := range fields {
			if fields[i] != oauthuserinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ouq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ouq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ouq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ouq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ouq *OAuthUserinfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ouq.driver.Dialect())
	t1 := builder.Table(oauthuserinfo.Table)
	columns := ouq.fields
	if len(columns) == 0 {
		columns = oauthuserinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ouq.sql != nil {
		selector = ouq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ouq.predicates {
		p(selector)
	}
	for _, p := range ouq.order {
		p(selector)
	}
	if offset := ouq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ouq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OAuthUserinfoGroupBy is the group-by builder for OAuthUserinfo entities.
type OAuthUserinfoGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ougb *OAuthUserinfoGroupBy) Aggregate(fns ...AggregateFunc) *OAuthUserinfoGroupBy {
	ougb.fns = append(ougb.fns, fns...)
	return ougb
}

// Scan applies the group-by query and scans the result into the given value.
func (ougb *OAuthUserinfoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ougb.path(ctx)
	if err != nil {
		return err
	}
	ougb.sql = query
	return ougb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ougb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ougb *OAuthUserinfoGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ougb.fields) > 1 {
		return nil, errors.New("ent: OAuthUserinfoGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ougb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) StringsX(ctx context.Context) []string {
	v, err := ougb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ougb *OAuthUserinfoGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ougb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = fmt.Errorf("ent: OAuthUserinfoGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) StringX(ctx context.Context) string {
	v, err := ougb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ougb *OAuthUserinfoGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ougb.fields) > 1 {
		return nil, errors.New("ent: OAuthUserinfoGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ougb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) IntsX(ctx context.Context) []int {
	v, err := ougb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ougb *OAuthUserinfoGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ougb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = fmt.Errorf("ent: OAuthUserinfoGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) IntX(ctx context.Context) int {
	v, err := ougb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ougb *OAuthUserinfoGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ougb.fields) > 1 {
		return nil, errors.New("ent: OAuthUserinfoGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ougb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ougb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ougb *OAuthUserinfoGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ougb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = fmt.Errorf("ent: OAuthUserinfoGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ougb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ougb *OAuthUserinfoGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ougb.fields) > 1 {
		return nil, errors.New("ent: OAuthUserinfoGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ougb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ougb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ougb *OAuthUserinfoGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ougb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = fmt.Errorf("ent: OAuthUserinfoGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ougb *OAuthUserinfoGroupBy) BoolX(ctx context.Context) bool {
	v, err := ougb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ougb *OAuthUserinfoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ougb.fields {
		if !oauthuserinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ougb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ougb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ougb *OAuthUserinfoGroupBy) sqlQuery() *sql.Selector {
	selector := ougb.sql.Select()
	aggregation := make([]string, 0, len(ougb.fns))
	for _, fn := range ougb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ougb.fields)+len(ougb.fns))
		for _, f := range ougb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ougb.fields...)...)
}

// OAuthUserinfoSelect is the builder for selecting fields of OAuthUserinfo entities.
type OAuthUserinfoSelect struct {
	*OAuthUserinfoQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ous *OAuthUserinfoSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ous.prepareQuery(ctx); err != nil {
		return err
	}
	ous.sql = ous.OAuthUserinfoQuery.sqlQuery(ctx)
	return ous.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ous.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ous *OAuthUserinfoSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ous.fields) > 1 {
		return nil, errors.New("ent: OAuthUserinfoSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ous.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) StringsX(ctx context.Context) []string {
	v, err := ous.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ous *OAuthUserinfoSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ous.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = fmt.Errorf("ent: OAuthUserinfoSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) StringX(ctx context.Context) string {
	v, err := ous.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ous *OAuthUserinfoSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ous.fields) > 1 {
		return nil, errors.New("ent: OAuthUserinfoSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ous.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) IntsX(ctx context.Context) []int {
	v, err := ous.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ous *OAuthUserinfoSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ous.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = fmt.Errorf("ent: OAuthUserinfoSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) IntX(ctx context.Context) int {
	v, err := ous.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ous *OAuthUserinfoSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ous.fields) > 1 {
		return nil, errors.New("ent: OAuthUserinfoSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ous.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ous.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ous *OAuthUserinfoSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ous.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = fmt.Errorf("ent: OAuthUserinfoSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) Float64X(ctx context.Context) float64 {
	v, err := ous.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ous *OAuthUserinfoSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ous.fields) > 1 {
		return nil, errors.New("ent: OAuthUserinfoSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ous.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) BoolsX(ctx context.Context) []bool {
	v, err := ous.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ous *OAuthUserinfoSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ous.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{oauthuserinfo.Label}
	default:
		err = fmt.Errorf("ent: OAuthUserinfoSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ous *OAuthUserinfoSelect) BoolX(ctx context.Context) bool {
	v, err := ous.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ous *OAuthUserinfoSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ous.sql.Query()
	if err := ous.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
