// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"enttest/ent/oauth"
	"enttest/ent/predicate"
	"enttest/ent/schema"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OAuthUpdate is the builder for updating OAuth entities.
type OAuthUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthMutation
}

// Where appends a list predicates to the OAuthUpdate builder.
func (ou *OAuthUpdate) Where(ps ...predicate.OAuth) *OAuthUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetName sets the "name" field.
func (ou *OAuthUpdate) SetName(s string) *OAuthUpdate {
	ou.mutation.SetName(s)
	return ou
}

// SetMethod sets the "method" field.
func (ou *OAuthUpdate) SetMethod(s string) *OAuthUpdate {
	ou.mutation.SetMethod(s)
	return ou
}

// SetIcon sets the "icon" field.
func (ou *OAuthUpdate) SetIcon(s string) *OAuthUpdate {
	ou.mutation.SetIcon(s)
	return ou
}

// SetAppid sets the "appid" field.
func (ou *OAuthUpdate) SetAppid(s string) *OAuthUpdate {
	ou.mutation.SetAppid(s)
	return ou
}

// SetSecret sets the "secret" field.
func (ou *OAuthUpdate) SetSecret(s string) *OAuthUpdate {
	ou.mutation.SetSecret(s)
	return ou
}

// SetResourceURI sets the "resource_uri" field.
func (ou *OAuthUpdate) SetResourceURI(su schema.ResourceURI) *OAuthUpdate {
	ou.mutation.SetResourceURI(su)
	return ou
}

// SetScope sets the "scope" field.
func (ou *OAuthUpdate) SetScope(s []string) *OAuthUpdate {
	ou.mutation.SetScope(s)
	return ou
}

// Mutation returns the OAuthMutation object of the builder.
func (ou *OAuthUpdate) Mutation() *OAuthMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OAuthUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ou.hooks) == 0 {
		affected, err = ou.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OAuthMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ou.mutation = mutation
			affected, err = ou.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ou.hooks) - 1; i >= 0; i-- {
			if ou.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ou.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ou.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OAuthUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OAuthUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OAuthUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ou *OAuthUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   oauth.Table,
			Columns: oauth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauth.FieldID,
			},
		},
	}
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldName,
		})
	}
	if value, ok := ou.mutation.Method(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldMethod,
		})
	}
	if value, ok := ou.mutation.Icon(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldIcon,
		})
	}
	if value, ok := ou.mutation.Appid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldAppid,
		})
	}
	if value, ok := ou.mutation.Secret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldSecret,
		})
	}
	if value, ok := ou.mutation.ResourceURI(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: oauth.FieldResourceURI,
		})
	}
	if value, ok := ou.mutation.Scope(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: oauth.FieldScope,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// OAuthUpdateOne is the builder for updating a single OAuth entity.
type OAuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthMutation
}

// SetName sets the "name" field.
func (ouo *OAuthUpdateOne) SetName(s string) *OAuthUpdateOne {
	ouo.mutation.SetName(s)
	return ouo
}

// SetMethod sets the "method" field.
func (ouo *OAuthUpdateOne) SetMethod(s string) *OAuthUpdateOne {
	ouo.mutation.SetMethod(s)
	return ouo
}

// SetIcon sets the "icon" field.
func (ouo *OAuthUpdateOne) SetIcon(s string) *OAuthUpdateOne {
	ouo.mutation.SetIcon(s)
	return ouo
}

// SetAppid sets the "appid" field.
func (ouo *OAuthUpdateOne) SetAppid(s string) *OAuthUpdateOne {
	ouo.mutation.SetAppid(s)
	return ouo
}

// SetSecret sets the "secret" field.
func (ouo *OAuthUpdateOne) SetSecret(s string) *OAuthUpdateOne {
	ouo.mutation.SetSecret(s)
	return ouo
}

// SetResourceURI sets the "resource_uri" field.
func (ouo *OAuthUpdateOne) SetResourceURI(su schema.ResourceURI) *OAuthUpdateOne {
	ouo.mutation.SetResourceURI(su)
	return ouo
}

// SetScope sets the "scope" field.
func (ouo *OAuthUpdateOne) SetScope(s []string) *OAuthUpdateOne {
	ouo.mutation.SetScope(s)
	return ouo
}

// Mutation returns the OAuthMutation object of the builder.
func (ouo *OAuthUpdateOne) Mutation() *OAuthMutation {
	return ouo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OAuthUpdateOne) Select(field string, fields ...string) *OAuthUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated OAuth entity.
func (ouo *OAuthUpdateOne) Save(ctx context.Context) (*OAuth, error) {
	var (
		err  error
		node *OAuth
	)
	if len(ouo.hooks) == 0 {
		node, err = ouo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OAuthMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ouo.mutation = mutation
			node, err = ouo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ouo.hooks) - 1; i >= 0; i-- {
			if ouo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ouo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ouo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OAuthUpdateOne) SaveX(ctx context.Context) *OAuth {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OAuthUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OAuthUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ouo *OAuthUpdateOne) sqlSave(ctx context.Context) (_node *OAuth, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   oauth.Table,
			Columns: oauth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauth.FieldID,
			},
		},
	}
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing OAuth.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauth.FieldID)
		for _, f := range fields {
			if !oauth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldName,
		})
	}
	if value, ok := ouo.mutation.Method(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldMethod,
		})
	}
	if value, ok := ouo.mutation.Icon(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldIcon,
		})
	}
	if value, ok := ouo.mutation.Appid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldAppid,
		})
	}
	if value, ok := ouo.mutation.Secret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth.FieldSecret,
		})
	}
	if value, ok := ouo.mutation.ResourceURI(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: oauth.FieldResourceURI,
		})
	}
	if value, ok := ouo.mutation.Scope(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: oauth.FieldScope,
		})
	}
	_node = &OAuth{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
