// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"enttest/ent/oauthuserinfo"
	"enttest/ent/predicate"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OAuthUserinfoDelete is the builder for deleting a OAuthUserinfo entity.
type OAuthUserinfoDelete struct {
	config
	hooks    []Hook
	mutation *OAuthUserinfoMutation
}

// Where appends a list predicates to the OAuthUserinfoDelete builder.
func (oud *OAuthUserinfoDelete) Where(ps ...predicate.OAuthUserinfo) *OAuthUserinfoDelete {
	oud.mutation.Where(ps...)
	return oud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oud *OAuthUserinfoDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(oud.hooks) == 0 {
		affected, err = oud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OAuthUserinfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			oud.mutation = mutation
			affected, err = oud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(oud.hooks) - 1; i >= 0; i-- {
			if oud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = oud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, oud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (oud *OAuthUserinfoDelete) ExecX(ctx context.Context) int {
	n, err := oud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oud *OAuthUserinfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: oauthuserinfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauthuserinfo.FieldID,
			},
		},
	}
	if ps := oud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, oud.driver, _spec)
}

// OAuthUserinfoDeleteOne is the builder for deleting a single OAuthUserinfo entity.
type OAuthUserinfoDeleteOne struct {
	oud *OAuthUserinfoDelete
}

// Exec executes the deletion query.
func (oudo *OAuthUserinfoDeleteOne) Exec(ctx context.Context) error {
	n, err := oudo.oud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthuserinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oudo *OAuthUserinfoDeleteOne) ExecX(ctx context.Context) {
	oudo.oud.ExecX(ctx)
}
