// Code generated by entc, DO NOT EDIT.

package oauth

const (
	// Label holds the string label denoting the oauth type in the database.
	Label = "oauth"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldAppid holds the string denoting the appid field in the database.
	FieldAppid = "appid"
	// FieldSecret holds the string denoting the secret field in the database.
	FieldSecret = "secret"
	// FieldResourceURI holds the string denoting the resource_uri field in the database.
	FieldResourceURI = "resource_uri"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// Table holds the table name of the oauth in the database.
	Table = "oauths"
)

// Columns holds all SQL columns for oauth fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldMethod,
	FieldIcon,
	FieldAppid,
	FieldSecret,
	FieldResourceURI,
	FieldScope,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
