// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// OAuth is the predicate function for oauth builders.
type OAuth func(*sql.Selector)

// OAuthUserinfo is the predicate function for oauthuserinfo builders.
type OAuthUserinfo func(*sql.Selector)
